---
apiVersion: v1
kind: Service
metadata:
  name: grpc-example
  labels:
    type: grpc
    service: grpc-example
spec:
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
  selector:
    name: grpc-example
