// Code generated by protoc-gen-go.
// source: pb/helloworld.proto
// DO NOT EDIT!

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	pb/helloworld.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	FileRequest
	FileReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FileRequest struct {
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (m *FileRequest) Reset()                    { *m = FileRequest{} }
func (m *FileRequest) String() string            { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()               {}
func (*FileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type FileReply struct {
	Image  []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *FileReply) Reset()                    { *m = FileReply{} }
func (m *FileReply) String() string            { return proto.CompactTextString(m) }
func (*FileReply) ProtoMessage()               {}
func (*FileReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileReply) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *FileReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*FileRequest)(nil), "helloworld.FileRequest")
	proto.RegisterType((*FileReply)(nil), "helloworld.FileReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloStreamServer(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloStreamServerClient, error)
	SayHelloStreamClient(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStreamClientClient, error)
	FileProcess(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloStreamServer(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloStreamServerClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Greeter_serviceDesc.Streams[0], c.cc, "/helloworld.Greeter/SayHelloStreamServer", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStreamServerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayHelloStreamServerClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloStreamServerClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStreamServerClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloStreamClient(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStreamClientClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Greeter_serviceDesc.Streams[1], c.cc, "/helloworld.Greeter/SayHelloStreamClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStreamClientClient{stream}
	return x, nil
}

type Greeter_SayHelloStreamClientClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloStreamClientClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStreamClientClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloStreamClientClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) FileProcess(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error) {
	out := new(FileReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/FileProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloStreamServer(*HelloRequest, Greeter_SayHelloStreamServerServer) error
	SayHelloStreamClient(Greeter_SayHelloStreamClientServer) error
	FileProcess(context.Context, *FileRequest) (*FileReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloStreamServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayHelloStreamServer(m, &greeterSayHelloStreamServerServer{stream})
}

type Greeter_SayHelloStreamServerServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayHelloStreamServerServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStreamServerServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayHelloStreamClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloStreamClient(&greeterSayHelloStreamClientServer{stream})
}

type Greeter_SayHelloStreamClientServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloStreamClientServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStreamClientServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloStreamClientServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_FileProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).FileProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/FileProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).FileProcess(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "FileProcess",
			Handler:    _Greeter_FileProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloStreamServer",
			Handler:       _Greeter_SayHelloStreamServer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloStreamClient",
			Handler:       _Greeter_SayHelloStreamClient_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pb/helloworld.proto",
}

func init() { proto.RegisterFile("pb/helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0xd1, 0xd6, 0x8e, 0x05, 0x61, 0xac, 0x35, 0xd4, 0x8b, 0xac, 0x20, 0x3d, 0xc5,
	0xa2, 0x27, 0x2f, 0x0a, 0x15, 0xd4, 0x83, 0x87, 0x92, 0x1c, 0x3c, 0xa7, 0x75, 0xa8, 0x81, 0x4d,
	0x77, 0x9d, 0xdd, 0xaa, 0x79, 0x21, 0x9f, 0x53, 0xb2, 0xe9, 0xe2, 0x42, 0x7b, 0xea, 0x6d, 0xbe,
	0x9d, 0xdf, 0x7e, 0xf3, 0x87, 0x81, 0x13, 0x3d, 0xbb, 0xfe, 0x20, 0x29, 0xd5, 0xb7, 0x62, 0xf9,
	0x9e, 0x68, 0x56, 0x56, 0x21, 0xfc, 0xbf, 0x08, 0x01, 0xbd, 0x97, 0x5a, 0xa5, 0xf4, 0xb9, 0x22,
	0x63, 0x11, 0x61, 0x7f, 0x99, 0x97, 0x14, 0x47, 0x17, 0xd1, 0xa8, 0x9b, 0xba, 0x58, 0x5c, 0x01,
	0xac, 0x19, 0x2d, 0x2b, 0x8c, 0xa1, 0x53, 0x92, 0x31, 0xf9, 0xc2, 0x43, 0x5e, 0x8a, 0x4b, 0x38,
	0x7a, 0x2a, 0x24, 0x79, 0xab, 0x3e, 0x1c, 0x14, 0xa5, 0xc7, 0x7a, 0x69, 0x23, 0xc4, 0x1d, 0x74,
	0x1b, 0xa8, 0xf6, 0xda, 0x8a, 0xe0, 0x00, 0xda, 0x4c, 0x66, 0x25, 0x6d, 0xdc, 0x72, 0x05, 0xd6,
	0xea, 0xe6, 0xb7, 0x05, 0x9d, 0x67, 0x26, 0xb2, 0xc4, 0x78, 0x0f, 0x87, 0x59, 0x5e, 0xb9, 0xb6,
	0x30, 0x4e, 0x82, 0x11, 0xc3, 0x69, 0x86, 0x83, 0x2d, 0x19, 0x2d, 0x2b, 0xb1, 0x87, 0xaf, 0xd0,
	0xf7, 0xff, 0x33, 0xcb, 0x94, 0x97, 0x19, 0xf1, 0x17, 0xf1, 0x2e, 0x5e, 0xe3, 0x68, 0xd3, 0xed,
	0x51, 0x16, 0xb4, 0xb4, 0xbb, 0xb8, 0x8d, 0x22, 0x7c, 0x68, 0xf6, 0x38, 0x65, 0x35, 0x27, 0x63,
	0xf0, 0x2c, 0x44, 0x83, 0x05, 0x0f, 0x4f, 0x37, 0x13, 0xce, 0x62, 0x32, 0x86, 0xf3, 0x42, 0x25,
	0x0b, 0xd6, 0xf3, 0x84, 0x7e, 0xf2, 0x52, 0x4b, 0x32, 0x01, 0x3a, 0x39, 0x76, 0xf5, 0xde, 0xea,
	0x78, 0x5a, 0x1f, 0xc4, 0x34, 0x9a, 0xb5, 0xdd, 0x65, 0xdc, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x75, 0xf4, 0x03, 0x9b, 0x30, 0x02, 0x00, 0x00,
}
