// Code generated by protoc-gen-go.
// source: pb/helloworld.proto
// DO NOT EDIT!

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	pb/helloworld.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	FileRequest
	FileReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FileRequest struct {
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (m *FileRequest) Reset()                    { *m = FileRequest{} }
func (m *FileRequest) String() string            { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()               {}
func (*FileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type FileReply struct {
	Image  []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *FileReply) Reset()                    { *m = FileReply{} }
func (m *FileReply) String() string            { return proto.CompactTextString(m) }
func (*FileReply) ProtoMessage()               {}
func (*FileReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileReply) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *FileReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*FileRequest)(nil), "helloworld.FileRequest")
	proto.RegisterType((*FileReply)(nil), "helloworld.FileReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayStreamHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayStreamHelloClient, error)
	FileProcess(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayStreamHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayStreamHelloClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Greeter_serviceDesc.Streams[0], c.cc, "/helloworld.Greeter/SayStreamHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayStreamHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayStreamHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayStreamHelloClient struct {
	grpc.ClientStream
}

func (x *greeterSayStreamHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) FileProcess(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error) {
	out := new(FileReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/FileProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayStreamHello(*HelloRequest, Greeter_SayStreamHelloServer) error
	FileProcess(context.Context, *FileRequest) (*FileReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayStreamHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayStreamHello(m, &greeterSayStreamHelloServer{stream})
}

type Greeter_SayStreamHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayStreamHelloServer struct {
	grpc.ServerStream
}

func (x *greeterSayStreamHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_FileProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).FileProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/FileProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).FileProcess(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "FileProcess",
			Handler:    _Greeter_FileProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayStreamHello",
			Handler:       _Greeter_SayStreamHello_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/helloworld.proto",
}

func init() { proto.RegisterFile("pb/helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x8d, 0x68, 0x6b, 0xc7, 0xa2, 0x30, 0x6a, 0x5d, 0xea, 0x45, 0x22, 0x88, 0xa7, 0xb5,
	0xe8, 0xc9, 0x8b, 0x42, 0x0f, 0xd5, 0xe3, 0xb2, 0x7b, 0xf0, 0x9c, 0xd6, 0xa1, 0x2e, 0x24, 0x26,
	0x26, 0x29, 0xba, 0x7f, 0xd3, 0x5f, 0x24, 0x9b, 0x6d, 0x30, 0x60, 0x4f, 0xbd, 0xcd, 0xcb, 0x7c,
	0xbc, 0xc9, 0x9b, 0x81, 0x13, 0x33, 0xbf, 0x7d, 0x27, 0x29, 0xf5, 0x97, 0xb6, 0xf2, 0x2d, 0x37,
	0x56, 0x7b, 0x8d, 0xf0, 0xf7, 0xc2, 0x39, 0x0c, 0x5f, 0x5a, 0x55, 0xd2, 0xe7, 0x8a, 0x9c, 0x47,
	0x84, 0xbd, 0x0f, 0xa1, 0x28, 0x63, 0x97, 0xec, 0x66, 0x50, 0x86, 0x9a, 0x5f, 0x03, 0xac, 0x19,
	0x23, 0x1b, 0xcc, 0xa0, 0xaf, 0xc8, 0x39, 0xb1, 0x8c, 0x50, 0x94, 0xfc, 0x0a, 0x0e, 0x67, 0xb5,
	0xa4, 0x68, 0x75, 0x0a, 0xfb, 0xb5, 0x8a, 0xd8, 0xb0, 0xec, 0x04, 0x7f, 0x80, 0x41, 0x07, 0xb5,
	0x5e, 0x1b, 0x11, 0x1c, 0x41, 0xcf, 0x92, 0x5b, 0x49, 0x9f, 0xed, 0x86, 0x01, 0x6b, 0x75, 0xf7,
	0xc3, 0xa0, 0xff, 0x6c, 0x89, 0x3c, 0x59, 0x7c, 0x84, 0x83, 0x4a, 0x34, 0xe1, 0x5b, 0x98, 0xe5,
	0x49, 0xc4, 0x34, 0xcd, 0x78, 0xb4, 0xa1, 0x63, 0x64, 0xc3, 0x77, 0x70, 0x06, 0x47, 0x95, 0x68,
	0x2a, 0x6f, 0x49, 0xa8, 0xad, 0x5d, 0x26, 0x0c, 0x9f, 0xba, 0xcc, 0x85, 0xd5, 0x0b, 0x72, 0x0e,
	0xcf, 0x53, 0x34, 0x59, 0xc6, 0xf8, 0xec, 0x7f, 0x23, 0x58, 0x4c, 0x27, 0x70, 0x51, 0xeb, 0x7c,
	0x69, 0xcd, 0x22, 0xa7, 0x6f, 0xa1, 0x8c, 0x24, 0x97, 0xa0, 0xd3, 0xe3, 0x30, 0xef, 0xb5, 0xad,
	0x8b, 0xf6, 0x78, 0x05, 0x9b, 0xf7, 0xc2, 0x15, 0xef, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfb,
	0x58, 0x54, 0x6c, 0xdc, 0x01, 0x00, 0x00,
}
